"""relationship change

Revision ID: ade23c08eff6
Revises: 
Create Date: 2021-03-10 20:10:19.589447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade23c08eff6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.String(length=16), nullable=False),
    sa.Column('link', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('subtitle', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry', sa.String(length=512), nullable=True),
    sa.Column('translation', sa.String(length=512), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('e_type', sa.String(length=12), nullable=True),
    sa.Column('article', sa.String(length=3), nullable=True),
    sa.Column('plural', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.lesson_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_article'), 'entry', ['article'], unique=False)
    op.create_index(op.f('ix_entry_e_type'), 'entry', ['e_type'], unique=False)
    op.create_index(op.f('ix_entry_entry'), 'entry', ['entry'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_entry'), table_name='entry')
    op.drop_index(op.f('ix_entry_e_type'), table_name='entry')
    op.drop_index(op.f('ix_entry_article'), table_name='entry')
    op.drop_table('entry')
    op.drop_table('lesson')
    # ### end Alembic commands ###
